name: Build and Push to ECR

on:
  push:
    tags:
      - 'v*'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ops3-ecr
  MOTD: ArtofBugs

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    # Don't run unless lint passes for Dockerfile
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.ref_name }} .

      - name: Smoke test
        run: |
          docker run -d -p 25565:25565 --name smoke-test -v mc_data:/opt/minecraft/world:rw -e MOTD=${{ env.MOTD }} ${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}
          for i in $(seq 1 33); do
            sleep 10
            # Check if 'Done' exists in the logs
            if docker logs smoke-test | grep -q 'Done'; then
              echo "Smoke test passed!"
              STATUS=0
              break
            else
              echo "Waiting for 'Done' in logs... (Attempt $i/33)"
            fi
          done
          docker stop smoke-test
          docker rm smoke-test
          if [ $STATUS != 0 ]; then
            echo "Smoke test failed with status $STATUS, 'Done' not found in logs."
            exit 1
          fi

      - name: Tag and push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.ref_name }} \
            $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}
